services:
  - type: web
    name: quizbuilder-ai
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r ./backend/requirements.txt
    startCommand: cd backend && python3 start_production.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
